# Generated by Django 5.2 on 2025-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yetenek',
            name='seviye',
            field=models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('iyi', 'İyi'), ('cokiyi', 'Çok İyi'), ('uzman', 'Uzman')], default='iyi', help_text='Bu yetenekteki uzmanlık seviyeniz', verbose_name='Seviye'),
        ),
    ]
