# Generated by Django 5.2 on 2025-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0002_alter_yetenek_seviye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istecrubesi',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Yaptığınız işler ve sorumluluklar hakkında bilgi', null=True, verbose_name='Açıklama'),
        ),
    ]
