# Generated by Django 5.2 on 2025-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0003_alter_istecrubesi_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istecrubesi',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Yaptığınız işler ve sorumluluklar hakkında bilgi', max_length=1000, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='ustalikalani',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Bu meslekteki ustalık hizmetleriniz hakkında bilgi', max_length=1000, null=True, verbose_name='Açıklama'),
        ),
    ]
