# Generated by Django 5.2 on 2025-04-10 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ayarlar', '0001_initial'),
        ('hesap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='İlanı benzersiz şekilde tanımlayan UUID', unique=True)),
                ('baslik', models.CharField(help_text='İş ilanının başlığı', max_length=200, verbose_name='İlan Başlığı')),
                ('slug', models.SlugField(blank=True, help_text="İlanın URL'de kullanılacak kısa adı", max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('pozisyon', models.CharField(help_text='İş pozisyonu/ünvanı', max_length=100, verbose_name='Pozisyon')),
                ('aciklama', models.TextField(help_text='İş hakkında detaylı açıklama', verbose_name='İş Açıklaması')),
                ('departman', models.CharField(blank=True, help_text='İşin hangi departmanda olduğu', max_length=100, null=True, verbose_name='Departman')),
                ('calisma_modeli', models.CharField(choices=[('tam_zamanli', 'Tam Zamanlı'), ('yari_zamanli', 'Yarı Zamanlı'), ('proje_bazli', 'Proje Bazlı'), ('stajyer', 'Stajyer'), ('gunluk', 'Günlük'), ('donusumlu', 'Dönüşümlü')], default='tam_zamanli', help_text='İşin çalışma şekli (tam zamanlı, yarı zamanlı vb.)', max_length=20, verbose_name='Çalışma Modeli')),
                ('calisma_yeri', models.CharField(choices=[('ofiste', 'Ofiste'), ('uzaktan', 'Uzaktan'), ('hibrit', 'Hibrit')], default='ofiste', help_text='İşin yapılacağı yer (ofiste, uzaktan vb.)', max_length=20, verbose_name='Çalışma Yeri')),
                ('adres', models.TextField(blank=True, help_text='İş yerinin açık adresi', null=True, verbose_name='Adres')),
                ('gerekli_nitelikler', models.TextField(help_text='Adayda bulunması gereken nitelikler', verbose_name='Gerekli Nitelikler')),
                ('tercih_nitelikleri', models.TextField(blank=True, help_text='Adayda bulunması tercih edilen ancak zorunlu olmayan nitelikler', null=True, verbose_name='Tercih Nedeni Nitelikler')),
                ('egitim_duzey', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('onlisans', 'Önlisans'), ('lisans', 'Lisans'), ('yuksek_lisans', 'Yüksek Lisans'), ('doktora', 'Doktora'), ('farketmez', 'Farketmez')], default='farketmez', help_text='Aranan minimum eğitim düzeyi', max_length=20, verbose_name='Eğitim Düzeyi')),
                ('deneyim_duzey', models.CharField(choices=[('deneyimsiz', 'Deneyimsiz'), ('stajyer', 'Stajyer'), ('az_tecrubeli', 'Az Tecrübeli (0-2 Yıl)'), ('orta_tecrubeli', 'Orta Tecrübeli (2-5 Yıl)'), ('tecrubeli', 'Tecrübeli (5-10 Yıl)'), ('uzman', 'Uzman (10+ Yıl)'), ('farketmez', 'Farketmez')], default='farketmez', help_text='Aranan deneyim düzeyi', max_length=20, verbose_name='Deneyim Düzeyi')),
                ('maas_bilgisi', models.CharField(blank=True, help_text='Maaş aralığı veya bilgisi (ör: 10.000TL-15.000TL)', max_length=100, null=True, verbose_name='Maaş Bilgisi')),
                ('maas_gizli', models.BooleanField(default=True, help_text='Maaş bilgisinin ilanda gizlenmesi', verbose_name='Maaş Bilgisi Gizli')),
                ('yan_haklar', models.TextField(blank=True, help_text='Sunulan yan haklar (yemek, servis, sağlık sigortası vb.)', null=True, verbose_name='Yan Haklar')),
                ('basvuru_baslangic', models.DateField(help_text='Başvuruların kabul edilmeye başlanacağı tarih', verbose_name='Başvuru Başlangıç Tarihi')),
                ('basvuru_bitis', models.DateField(blank=True, help_text='Başvuruların kabul edileceği son tarih (boş ise süresiz)', null=True, verbose_name='Son Başvuru Tarihi')),
                ('beklenen_basvuru', models.PositiveIntegerField(blank=True, help_text='Beklenen yaklaşık başvuru sayısı', null=True, verbose_name='Beklenen Başvuru Sayısı')),
                ('alinacak_kisi', models.PositiveIntegerField(default=1, help_text='Alınacak kişi sayısı', verbose_name='Alınacak Kişi Sayısı')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('yayinda', 'Yayında'), ('durduruldu', 'Durduruldu'), ('sonlandi', 'Sonlandırıldı'), ('iptal', 'İptal Edildi')], default='taslak', help_text='İlanın mevcut durumu', max_length=20, verbose_name='İlan Durumu')),
                ('one_cikartilmis', models.BooleanField(default=False, help_text='İlanın öne çıkartılmış olup olmadığı', verbose_name='Öne Çıkartılmış')),
                ('basvuru_sayisi', models.PositiveIntegerField(default=0, help_text='İlana yapılan başvuru sayısı', verbose_name='Başvuru Sayısı')),
                ('goruntuleme_sayisi', models.PositiveIntegerField(default=0, help_text='İlanın görüntülenme sayısı', verbose_name='Görüntülenme Sayısı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, help_text='İlanın oluşturulduğu tarih', verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, help_text='İlanın son güncellendiği tarih', verbose_name='Güncellenme Tarihi')),
                ('yayinlanma_tarihi', models.DateTimeField(blank=True, help_text='İlanın yayınlandığı tarih', null=True, verbose_name='Yayınlanma Tarihi')),
                ('firma', models.ForeignKey(help_text='İlanı yayınlayan firma', on_delete=django.db.models.deletion.CASCADE, related_name='is_ilanlari', to='hesap.firma', verbose_name='Firma')),
                ('il', models.ForeignKey(blank=True, help_text='İşin yapılacağı il', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_ilanlari', to='ayarlar.il', verbose_name='İl')),
                ('ilce', models.ForeignKey(blank=True, help_text='İşin yapılacağı ilçe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_ilanlari', to='ayarlar.ilce', verbose_name='İlçe')),
                ('sektor', models.ForeignKey(blank=True, help_text='İlanın ilgili olduğu sektör', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_ilanlari', to='ayarlar.sektor', verbose_name='Sektör')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IlanSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(help_text='Başvuru sırasında sorulacak soru', max_length=255, verbose_name='Soru')),
                ('soru_tipi', models.CharField(choices=[('metin', 'Metin'), ('coktan_secmeli', 'Çoktan Seçmeli'), ('evet_hayir', 'Evet/Hayır')], default='metin', help_text='Sorunun cevap tipi', max_length=20, verbose_name='Soru Tipi')),
                ('secenekler', models.TextField(blank=True, help_text='Çoktan seçmeli soru için seçenekler (her satıra bir seçenek)', null=True, verbose_name='Seçenekler')),
                ('zorunlu', models.BooleanField(default=True, help_text='Bu soruya cevap verilmesinin zorunlu olup olmadığı', verbose_name='Zorunlu')),
                ('sira', models.PositiveSmallIntegerField(default=0, help_text='Sorunun görüntülenme sırası', verbose_name='Sıra')),
                ('ilan', models.ForeignKey(help_text='Bu sorunun bağlı olduğu ilan', on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='ilanlar.isbilgileri', verbose_name='İş İlanı')),
            ],
            options={
                'verbose_name': 'İlan Soru',
                'verbose_name_plural': 'İlan Soruları',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='IlanDil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(help_text='İstenen dil', max_length=50, verbose_name='Dil')),
                ('seviye', models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('iyi', 'İyi'), ('cok_iyi', 'Çok İyi'), ('ileri', 'İleri'), ('anadil', 'Anadil')], default='orta', help_text='İstenen dil seviyesi', max_length=10, verbose_name='Seviye')),
                ('zorunlu', models.BooleanField(default=True, help_text='Bu dilin zorunlu olup olmadığı', verbose_name='Zorunlu')),
                ('ilan', models.ForeignKey(help_text='Bu dil şartının bağlı olduğu ilan', on_delete=django.db.models.deletion.CASCADE, related_name='istenen_diller', to='ilanlar.isbilgileri', verbose_name='İş İlanı')),
            ],
            options={
                'verbose_name': 'İlan Dil Şartı',
                'verbose_name_plural': 'İlan Dil Şartları',
                'unique_together': {('ilan', 'dil')},
            },
        ),
        migrations.CreateModel(
            name='IlanAnahtar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar_kelime', models.CharField(help_text='İlanla ilgili anahtar kelime', max_length=50, verbose_name='Anahtar Kelime')),
                ('ilan', models.ForeignKey(help_text='Bu anahtar kelimenin bağlı olduğu ilan', on_delete=django.db.models.deletion.CASCADE, related_name='anahtar_kelimeler', to='ilanlar.isbilgileri', verbose_name='İş İlanı')),
            ],
            options={
                'verbose_name': 'İlan Anahtar Kelime',
                'verbose_name_plural': 'İlan Anahtar Kelimeler',
                'unique_together': {('ilan', 'anahtar_kelime')},
            },
        ),
    ]
