# Generated by Django 5.2 on 2025-04-10 12:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0001_initial'),
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Başvuruyu benzersiz şekilde tanımlayan UUID', unique=True)),
                ('ozgecmis', models.FileField(blank=True, help_text='Başvuru için yüklenen özgeçmiş dosyası', null=True, upload_to='basvurular/ozgecmis/', verbose_name='Özgeçmiş')),
                ('on_yazi', models.TextField(blank=True, help_text='Başvuru için yazılan tanıtım/motivasyon yazısı', null=True, verbose_name='Ön Yazı')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('incelendi', 'İncelendi'), ('musakat', 'Mülakata Çağrıldı'), ('red', 'Reddedildi'), ('kabul', 'Kabul Edildi'), ('iptal', 'İptal Edildi')], default='beklemede', help_text='Başvurunun mevcut durumu', max_length=15, verbose_name='Durum')),
                ('degerlendirme_notu', models.TextField(blank=True, help_text='İşverenin başvuru hakkındaki değerlendirme notu', null=True, verbose_name='Değerlendirme Notu')),
                ('puan', models.PositiveSmallIntegerField(blank=True, help_text='Başvuruya verilen puan (1-10 arası)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puan')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True, help_text='Başvurunun yapıldığı tarih', verbose_name='Başvuru Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, help_text='Başvurunun son güncellenme tarihi', verbose_name='Güncelleme Tarihi')),
                ('son_islem_tarihi', models.DateTimeField(blank=True, help_text='Başvuru üzerinde yapılan son işlemin tarihi (durum değişikliği vb.)', null=True, verbose_name='Son İşlem Tarihi')),
                ('okundu', models.BooleanField(default=False, help_text='Başvurunun işveren tarafından okunup okunmadığı', verbose_name='Okundu')),
                ('favorilendi', models.BooleanField(default=False, help_text='Başvurunun işveren tarafından favorilere eklenip eklenmediği', verbose_name='Favorilendi')),
                ('ilan', models.ForeignKey(help_text='Başvuru yapılan iş ilanı', on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ilanlar.isbilgileri', verbose_name='İş İlanı')),
                ('vatandas', models.ForeignKey(help_text='İş ilanına başvuran kişi', on_delete=django.db.models.deletion.CASCADE, related_name='is_basvurulari', to='hesap.vatandas', verbose_name='Başvuran')),
            ],
            options={
                'verbose_name': 'İlan Başvuru',
                'verbose_name_plural': 'İlan Başvuruları',
                'ordering': ['-basvuru_tarihi'],
                'unique_together': {('ilan', 'vatandas')},
            },
        ),
        migrations.CreateModel(
            name='IlanSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False, help_text='İş ilanı sürecinin tamamlanıp tamamlanmadığı', verbose_name='Tamamlandı')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, help_text='İş ilanı sürecinin tamamlandığı tarih', null=True, verbose_name='Tamamlanma Tarihi')),
                ('toplam_basvuru', models.PositiveIntegerField(default=0, help_text='Alınan toplam başvuru sayısı', verbose_name='Toplam Başvuru')),
                ('mulakat_yapilan', models.PositiveIntegerField(default=0, help_text='Mülakat yapılan aday sayısı', verbose_name='Mülakat Yapılan')),
                ('ise_alinan', models.PositiveIntegerField(default=0, help_text='İşe alınan kişi sayısı', verbose_name='İşe Alınan')),
                ('aciklama', models.TextField(blank=True, help_text='İlan sonucu hakkında genel açıklama', null=True, verbose_name='Açıklama')),
                ('basari_puani', models.PositiveSmallIntegerField(blank=True, help_text='İş ilanı sürecinin başarı puanı (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Başarı Puanı')),
                ('ic_degerlendirme', models.TextField(blank=True, help_text='İlan süreci hakkında firma içi değerlendirme notları', null=True, verbose_name='İç Değerlendirme')),
                ('ilan', models.OneToOneField(help_text='Sonucun ait olduğu iş ilanı', on_delete=django.db.models.deletion.CASCADE, related_name='sonuc', to='ilanlar.isbilgileri', verbose_name='İş İlanı')),
                ('ise_alinanlar', models.ManyToManyField(blank=True, help_text='Bu ilanda işe alınan kişiler', related_name='ise_alinan_ilanlar', to='ilanlar.ilanbasvuru', verbose_name='İşe Alınanlar')),
            ],
            options={
                'verbose_name': 'İlan Sonucu',
                'verbose_name_plural': 'İlan Sonuçları',
            },
        ),
        migrations.CreateModel(
            name='BasvuruCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.TextField(help_text='Soruya verilen cevap', verbose_name='Cevap')),
                ('soru', models.ForeignKey(help_text='Cevaplanan soru', on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='ilanlar.ilansoru', verbose_name='Soru')),
                ('basvuru', models.ForeignKey(help_text='Bu cevabın ait olduğu başvuru', on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='ilanlar.ilanbasvuru', verbose_name='Başvuru')),
            ],
            options={
                'verbose_name': 'Başvuru Cevabı',
                'verbose_name_plural': 'Başvuru Cevapları',
                'unique_together': {('basvuru', 'soru')},
            },
        ),
    ]
